config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "application#index"

    resources :products, only: [:new, :create, :edit, :update, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  root :to => 'products#index'

  resources :products, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :excluding_archived, lambda {where(archived_at: nil)}

  validates :first_name, :last_name, presence: true

  def to_s
    "#{last_name}, #{first_name} - #{email} #{admin? ? "(Admin)" : ""}"
  end

  def archive
    self.update(archived_at: Time.now)
  end

  def active_for_authentication?
    super && archived_at.nil?
  end

  def inactive_message
    archived_at.nil? ? super : :archived
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!

  def index
  end

  private

  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin to do that."
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = 'Product has been created.'
      redirect_to @product
    else
      flash.now[:alert] = 'Product has not been created.'
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = 'Product has been updated.'
      redirect_to @product
    else
      flash.now[:alert] = "Product has not been updated."
      render "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    flash[:notice] = 'Product has been deleted.'
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :archive]

  def index
    @users = User.excluding_archived.order(:last_name)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User has been created."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been created."
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end
    if @user.update(user_params)
      flash[:notice] = "User has been updated."
      redirect_to admin_users_path
    else
      flash.now[:alert] = "User has not been updated."
      render "edit"
    end
  end

  def archive
    if @user == current_user
      flash[:alert] = "You cannot archive yourself!."
    else
      @user.archive
      flash[:notice] = "User has been archived."
    end

    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  private
  def set_product
    @product = Product.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The product you were looking for could not be found."
    redirect_to products_path
  end
  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << 'Eshop').join(' - ')
      end
    end
  end

  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/application/index.html.erb
<div class="row" id="admin">
  <div class="col-md-9">
    <header>
      <h1>Admin Area</h1>
    </header>
  </div>
  <div class="col-md-3">
    <h2>Admin Links</h2>
    <ul class="nav nav-stacked">
      <li><%= link_to "Users", admin_users_path %></li>
    </ul>
  </div>
</div>

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, product]) do |f| %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>

  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/products/edit.html.erb
<header>
  <h1>Edit Product</h1>
</header>

<%= render "form", product: @product %>

app/views/admin/products/new.html.erb
<header>
  <h1>New Product</h1>
</header>

<%= render 'form', product: @product %>

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |f| %>
   <%= f.input :first_name %>
   <%= f.input :last_name %>
   <%= f.input :email %>
   <%= f.input :password %>
   <%= f.input :admin, label: "Is an admin?" %>
   <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/users/edit.html.erb
<header>
  <h1>Edit User</h1>
</header>

<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<header>
  <h1>Users</h1>

  <ul class="actions">
    <li>
      <%= link_to "New User", new_admin_user_path, class: "new" %>
    </li>
  </ul>
</header>

<ul>
  <% @users.each do |user| %>
     <li><%= link_to user, [:admin, user] %></li>
  <% end  %>
</ul>

app/views/admin/users/new.html.erb
<header>
  <h1>New User</h1>
</header>

<%= render "form", user: @user %>

app/views/admin/users/show.html.erb
<header>
  <h1><%= @user %></h1>

  <ul class="actions">
    <li>
      <%= link_to "Edit User", [:edit, :admin, @user], class: "edit" %>
    </li>
    <li>
      <%= link_to "Archive User", [:archive, :admin, @user], method: :patch,
      data: {confirm: "Are you sure you want to archive this user?"},
      class: "delete" %>
    </li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      <% if content_for?(:title) %>
         <%= yield(:title) %>
      <% else  %>
         Eshop
      <% end  %>
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Eshop", root_path, class: "navbar-brand" %>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="collapse">
          <ul class="nav navbar-nav">
            <li class="<%= "active" if current_page?("/") %>">
              <%= link_to "Home", root_path %>
            </li>
            <% admins_only do %>
            <li>
              <%= link_to "Admin", admin_root_path %>
            </li>
            <% end  %>
            <% unless user_signed_in? %>
            <li class="<%= "active" if current_page?("/users/sign_up") %>">
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li class="<%= "active" if current_page?("/users/sign_in") %>">
              <%= link_to "Sign in", new_user_session_path %>
            </li>
            <% end  %>
          </ul>
          <% if user_signed_in? %>
          <div class="navbar-right">
            <p class="navbar-text">
              Signed in as <%= current_user.email %>
            </p>
            <ul class="nav navbar-nav">
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
    <% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>">
        <%= message %>
      </div>
    <% end  %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/products/index.html.erb
<header>
   <h1>Products</h1>

   <% admins_only do  %>
   <ul class="actions">
     <li>
       <%= link_to 'New Product', new_admin_product_path, class: "new" %>
     </li>
   </ul>
   <% end  %>

</header>

<div id="products">
  <% @products.each do |product| %>
     <h2><%= link_to product.name, product %></h2>
     <p><%= product.description %></p>
     <p><%= product.price %></p>
  <% end  %>
</div>

app/views/products/show.html.erb
<% title(@product.name)%>

<header>
  <h1><%= @product.name %></h1>

  <% admins_only do  %>
  <ul class="actions">
    <li>
      <%= link_to 'Edit Product',
      edit_admin_product_path(@product), class: "edit" %>
    </li>
    <li>
      <%= link_to'Delete Product',
      admin_product_path(@product),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this product?"},
      class: "delete" %>
    </li>
  </ul>
  <% end %>
</header>

<p><%= @product.description %></p>
<p><%= @product.price %></p>